package com.lautaroserrano.cryptotracker.core.presentation.util

import com.lautaroserrano.cryptotracker.R

fun getDrawableIdForCoin(symbol: String): Int {
    return when (symbol.uppercase()) {
        "ABT" -> R.drawable.abt
        "AC3" -> R.drawable.ac3
        "ACT" -> R.drawable.act
        "ADA" -> R.drawable.ada
        "ADB" -> R.drawable.adb
        "AE" -> R.drawable.ae
        "AEON" -> R.drawable.aeon
        "AGI" -> R.drawable.agi
        "AIT" -> R.drawable.ait
        "AKRO" -> R.drawable.akro
        "ALEPH" -> R.drawable.aleph
        "ALGO" -> R.drawable.algo
        "ALIS" -> R.drawable.alis
        "ALPHA" -> R.drawable.alpha
        "ALX" -> R.drawable.alx
        "AMB" -> R.drawable.amb
        "AMLT" -> R.drawable.amlt
        "ANC" -> R.drawable.anc
        "ANKR" -> R.drawable.ankr
        "ANT" -> R.drawable.ant
        "APPC" -> R.drawable.appc
        "APW" -> R.drawable.apw
        "AR" -> R.drawable.ar
        "ARDR" -> R.drawable.ardr
        "ARK" -> R.drawable.ark
        "ARMOR" -> R.drawable.armor
        "ARN" -> R.drawable.arn
        "ARO" -> R.drawable.aro
        "ATMI" -> R.drawable.atmi
        "ATOM" -> R.drawable.atom
        "AUTO" -> R.drawable.auto
        "AVAX" -> R.drawable.avax
        "AWC" -> R.drawable.awc
        "BAL" -> R.drawable.bal
        "BAND" -> R.drawable.band
        "BAO" -> R.drawable.bao
        "BAY" -> R.drawable.bay
        "BBR" -> R.drawable.bbr
        "BCD" -> R.drawable.bcd
        "BCHA" -> R.drawable.bcha
        "BIFI" -> R.drawable.bifi
        "BLK" -> R.drawable.blk
        "BLOCK" -> R.drawable.block
        "BLUE" -> R.drawable.blue
        "BLZ" -> R.drawable.blz
        "BNB" -> R.drawable.bnb
        "BNT" -> R.drawable.bnt
        "BONDLY" -> R.drawable.bondly
        "BORA" -> R.drawable.bora
        "BPT" -> R.drawable.bpt
        "BTC" -> R.drawable.btc
        "BTO" -> R.drawable.bto
        "BUNNY" -> R.drawable.bunny
        "BUSD" -> R.drawable.busd
        "BWT" -> R.drawable.bwt
        "BZ" -> R.drawable.bz
        "BZNT" -> R.drawable.bznt
        "BZRX" -> R.drawable.bzrx
        "C20" -> R.drawable.c20
        "CAKE" -> R.drawable.cake
        "CARD" -> R.drawable.card
        "CBAT" -> R.drawable.cbat
        "CBT" -> R.drawable.cbt
        "CDT" -> R.drawable.cdt
        "CELO" -> R.drawable.celo
        "CELR" -> R.drawable.celr
        "CENNZ" -> R.drawable.cennz
        "CFX" -> R.drawable.cfx
        "CHAI" -> R.drawable.chai
        "CHSB" -> R.drawable.chsb
        "CLO" -> R.drawable.clo
        "CLOAK" -> R.drawable.cloak
        "CLOUT" -> R.drawable.clout
        "CMT" -> R.drawable.cmt
        "CND" -> R.drawable.cnd
        "CNX" -> R.drawable.cnx
        "COSM" -> R.drawable.cosm
        "COTI" -> R.drawable.coti
        "COV" -> R.drawable.cov
        "COVA" -> R.drawable.cova
        "CPC" -> R.drawable.cpc
        "CRED" -> R.drawable.cred
        "CREP" -> R.drawable.crep
        "CRO" -> R.drawable.cro
        "CRPT" -> R.drawable.crpt
        "CSAI" -> R.drawable.csai
        "CTXC" -> R.drawable.ctxc
        "CVC" -> R.drawable.cvc
        "CVP" -> R.drawable.cvp
        "CVT" -> R.drawable.cvt
        "DAFI" -> R.drawable.dafi
        "DAI" -> R.drawable.dai
        "DASH" -> R.drawable.dash
        "DATX" -> R.drawable.datx
        "DBC" -> R.drawable.dbc
        "DCR" -> R.drawable.dcr
        "DCT" -> R.drawable.dct
        "DDD" -> R.drawable.ddd
        "DENT" -> R.drawable.dent
        "DERI" -> R.drawable.deri
        "DFI" -> R.drawable.dfi
        "DFT" -> R.drawable.dft
        "DFYN" -> R.drawable.dfyn
        "DGD" -> R.drawable.dgd
        "DGTX" -> R.drawable.dgtx
        "DIVI" -> R.drawable.divi
        "DNT" -> R.drawable.dnt
        "DOCK" -> R.drawable.dock
        "DODO" -> R.drawable.dodo
        "DOGE" -> R.drawable.doge
        "DOR" -> R.drawable.dor
        "DOT" -> R.drawable.dot
        "DROP" -> R.drawable.drop
        "DTX" -> R.drawable.dtx
        "DVF" -> R.drawable.dvf
        "EDG" -> R.drawable.edg
        "EFI" -> R.drawable.efi
        "EFX" -> R.drawable.efx
        "EGLD" -> R.drawable.egld
        "ELA" -> R.drawable.ela
        "ELEC" -> R.drawable.elec
        "EMC2" -> R.drawable.emc2
        "ENG" -> R.drawable.eng
        "ENJ" -> R.drawable.enj
        "EOS" -> R.drawable.eos
        "EOSDAC" -> R.drawable.eosdac
        "ERN" -> R.drawable.ern
        "ETH" -> R.drawable.eth
        "ETN" -> R.drawable.etn
        "ETP" -> R.drawable.etp
        "ETZ" -> R.drawable.etz
        "EVX" -> R.drawable.evx
        "EWT" -> R.drawable.ewt
        "EXRN" -> R.drawable.exrn
        "EXY" -> R.drawable.exy
        "FCT" -> R.drawable.fct
        "FEED" -> R.drawable.feed
        "FET" -> R.drawable.fet
        "FIL" -> R.drawable.fil
        "FILDA" -> R.drawable.filda
        "FOTA" -> R.drawable.fota
        "FRM" -> R.drawable.frm
        "FSN" -> R.drawable.fsn
        "FT" -> R.drawable.ft
        "FTM" -> R.drawable.ftm
        "FUEL" -> R.drawable.fuel
        "FUN" -> R.drawable.`fun`
        "GALA" -> R.drawable.gala
        "GDC" -> R.drawable.gdc
        "GNT" -> R.drawable.gnt
        "GO" -> R.drawable.go
        "GOC" -> R.drawable.goc
        "GOT" -> R.drawable.got
        "GT" -> R.drawable.gt
        "GTO" -> R.drawable.gto
        "GVT" -> R.drawable.gvt
        "GXS" -> R.drawable.gxs
        "HAKKA" -> R.drawable.hakka
        "HC" -> R.drawable.hc
        "HEDG" -> R.drawable.hedg
        "HEX" -> R.drawable.hex
        "HIVE" -> R.drawable.hive
        "HOT_X" -> R.drawable.hot_x
        "HPB" -> R.drawable.hpb
        "HSR" -> R.drawable.hsr
        "HT" -> R.drawable.ht
        "HUSD" -> R.drawable.husd
        "HVN" -> R.drawable.hvn
        "HYDRO" -> R.drawable.hydro
        "HZN" -> R.drawable.hzn
        "IBAT" -> R.drawable.ibat
        "ICN" -> R.drawable.icn
        "ICX" -> R.drawable.icx
        "IDAI" -> R.drawable.idai
        "IDEX" -> R.drawable.idex
        "IKNC" -> R.drawable.iknc
        "INS" -> R.drawable.ins
        "IOTX" -> R.drawable.iotx
        "IQ" -> R.drawable.iq
        "IREP" -> R.drawable.irep
        "IRIS" -> R.drawable.iris
        "ISUSD" -> R.drawable.isusd
        "IZRX" -> R.drawable.izrx
        "JST" -> R.drawable.jst
        "JUNO" -> R.drawable.juno
        "KEEP" -> R.drawable.keep
        "KEY" -> R.drawable.key
        "KIN" -> R.drawable.kin
        "KLAY" -> R.drawable.klay
        "KLV" -> R.drawable.klv
        "KMD" -> R.drawable.kmd
        "LAND" -> R.drawable.land
        "LCX" -> R.drawable.lcx
        "LDO" -> R.drawable.ldo
        "LEND" -> R.drawable.lend
        "LEO" -> R.drawable.leo
        "LINK" -> R.drawable.link
        "LKY" -> R.drawable.lky
        "LON" -> R.drawable.lon
        "LOOM" -> R.drawable.loom
        "LRC" -> R.drawable.lrc
        "LSK" -> R.drawable.lsk
        "LTC" -> R.drawable.ltc
        "LUNA" -> R.drawable.luna
        "LXT" -> R.drawable.lxt
        "MAN" -> R.drawable.man
        "MATH" -> R.drawable.math
        "MATIC" -> R.drawable.matic
        "MATTER" -> R.drawable.matter
        "MBC" -> R.drawable.mbc
        "MCO" -> R.drawable.mco
        "MCX" -> R.drawable.mcx
        "MEDX" -> R.drawable.medx
        "MFG" -> R.drawable.mfg
        "MFT" -> R.drawable.mft
        "MIM" -> R.drawable.mim
        "MITH" -> R.drawable.mith
        "MKR" -> R.drawable.mkr
        "MNGO" -> R.drawable.mngo
        "MOD" -> R.drawable.mod
        "MPL" -> R.drawable.mpl
        "MTA" -> R.drawable.mta
        "MTN" -> R.drawable.mtn
        "MVL" -> R.drawable.mvl
        "MVP" -> R.drawable.mvp
        "MWC" -> R.drawable.mwc
        "MXM" -> R.drawable.mxm
        "MYB" -> R.drawable.myb
        "NAS" -> R.drawable.nas
        "NAV" -> R.drawable.nav
        "NCASH" -> R.drawable.ncash
        "NEO" -> R.drawable.neo
        "NEX" -> R.drawable.nex
        "NEXXO" -> R.drawable.nexxo
        "NFT" -> R.drawable.nft
        "NGC" -> R.drawable.ngc
        "NIOX" -> R.drawable.niox
        "NKN" -> R.drawable.nkn
        "NLG" -> R.drawable.nlg
        "NMR" -> R.drawable.nmr
        "NOIA" -> R.drawable.noia
        "NPER" -> R.drawable.nper
        "NPXS" -> R.drawable.npxs
        "NRG" -> R.drawable.nrg
        "NULS" -> R.drawable.nuls
        "NXS" -> R.drawable.nxs
        "OAG" -> R.drawable.oag
        "OCN" -> R.drawable.ocn
        "OHM" -> R.drawable.ohm
        "OKB" -> R.drawable.okb
        "OLT" -> R.drawable.olt
        "OMG" -> R.drawable.omg
        "ONION" -> R.drawable.onion
        "ONT" -> R.drawable.ont
        "ORBS" -> R.drawable.orbs
        "ORC" -> R.drawable.orc
        "OSMO" -> R.drawable.osmo
        "OST" -> R.drawable.ost
        "OXT" -> R.drawable.oxt
        "PAI" -> R.drawable.pai
        "PAINT" -> R.drawable.paint
        "PAR" -> R.drawable.par
        "PBR" -> R.drawable.pbr
        "PERL" -> R.drawable.perl
        "PICKLE" -> R.drawable.pickle
        "PIVX" -> R.drawable.pivx
        "PLDAI" -> R.drawable.pldai
        "PLR" -> R.drawable.plr
        "PLUSDC" -> R.drawable.plusdc
        "PNG" -> R.drawable.png
        "PNK" -> R.drawable.pnk
        "POA" -> R.drawable.poa
        "POKT" -> R.drawable.pokt
        "POLS" -> R.drawable.pols
        "POLY" -> R.drawable.poly
        "POND" -> R.drawable.pond
        "POOL" -> R.drawable.pool
        "POWR" -> R.drawable.powr
        "PPAY" -> R.drawable.ppay
        "PRE" -> R.drawable.pre
        "PREMIA" -> R.drawable.premia
        "PROS" -> R.drawable.pros
        "PRQ" -> R.drawable.prq
        "PST" -> R.drawable.pst
        "QASH" -> R.drawable.qash
        "QI" -> R.drawable.qi
        "QKC" -> R.drawable.qkc
        "QLC" -> R.drawable.qlc
        "QSP" -> R.drawable.qsp
        "QTUM" -> R.drawable.qtum
        "QUICK" -> R.drawable.quick
        "RAE" -> R.drawable.rae
        "RARI" -> R.drawable.rari
        "RCN" -> R.drawable.rcn
        "RDN" -> R.drawable.rdn
        "REN" -> R.drawable.ren
        "RLC" -> R.drawable.rlc
        "ROOK" -> R.drawable.rook
        "ROSE" -> R.drawable.rose
        "RPX" -> R.drawable.rpx
        "RSR" -> R.drawable.rsr
        "RSV" -> R.drawable.rsv
        "RVN" -> R.drawable.rvn
        "SALT" -> R.drawable.salt
        "SAR" -> R.drawable.sar
        "SCRT" -> R.drawable.scrt
        "SEELE" -> R.drawable.seele
        "SEFI" -> R.drawable.sefi
        "SEM" -> R.drawable.sem
        "SFP" -> R.drawable.sfp
        "SHIB" -> R.drawable.shib
        "SHR" -> R.drawable.shr
        "SHUF" -> R.drawable.shuf
        "SIA" -> R.drawable.sia
        "SLT" -> R.drawable.slt
        "SMART" -> R.drawable.smart
        "SNM" -> R.drawable.snm
        "SNX" -> R.drawable.snx
        "SOL" -> R.drawable.sol
        "SOUL" -> R.drawable.soul
        "SPN" -> R.drawable.spn
        "STEP" -> R.drawable.step
        "STETH" -> R.drawable.steth
        "STMX" -> R.drawable.stmx
        "STPT" -> R.drawable.stpt
        "STRAT" -> R.drawable.strat
        "SUB" -> R.drawable.sub
        "SUQA" -> R.drawable.suqa
        "SUTER" -> R.drawable.suter
        "SWAP" -> R.drawable.swap
        "SWTH" -> R.drawable.swth
        "SXP" -> R.drawable.sxp
        "SYS" -> R.drawable.sys
        "TBTC" -> R.drawable.tbtc
        "TEL" -> R.drawable.tel
        "THETA" -> R.drawable.theta
        "TIO" -> R.drawable.tio
        "TNB" -> R.drawable.tnb
        "TNC" -> R.drawable.tnc
        "TNT" -> R.drawable.tnt
        "TORN" -> R.drawable.torn
        "TRAC" -> R.drawable.trac
        "TRB" -> R.drawable.trb
        "TRIBE" -> R.drawable.tribe
        "TRU" -> R.drawable.tru
        "TRYB" -> R.drawable.tryb
        "TUSD" -> R.drawable.tusd
        "TWT" -> R.drawable.twt
        "UFT" -> R.drawable.uft
        "ULT" -> R.drawable.ult
        "UMA" -> R.drawable.uma
        "UNFI" -> R.drawable.unfi
        "UNI" -> R.drawable.uni
        "UNN" -> R.drawable.unn
        "UPP" -> R.drawable.upp
        "USDC" -> R.drawable.usdc
        "USDP" -> R.drawable.usdp
        "USDS" -> R.drawable.usds
        "USDT" -> R.drawable.usdt
        "UUU" -> R.drawable.uuu
        "VALUE" -> R.drawable.value
        "VERI" -> R.drawable.veri
        "VIDT" -> R.drawable.vidt
        "VIN" -> R.drawable.vin
        "VITE" -> R.drawable.vite
        "VRS" -> R.drawable.vrs
        "VSP" -> R.drawable.vsp
        "VSYS" -> R.drawable.vsys
        "VTC" -> R.drawable.vtc
        "WABI" -> R.drawable.wabi
        "WBTC" -> R.drawable.wbtc
        "WHALE" -> R.drawable.whale
        "WING" -> R.drawable.wing
        "WINGS" -> R.drawable.wings
        "WOO" -> R.drawable.woo
        "WPR" -> R.drawable.wpr
        "WRX" -> R.drawable.wrx
        "WTC" -> R.drawable.wtc
        "WXT" -> R.drawable.wxt
        "XCHF" -> R.drawable.xchf
        "XHV" -> R.drawable.xhv
        "XLM" -> R.drawable.xlm
        "XLQ" -> R.drawable.xlq
        "XMX" -> R.drawable.xmx
        "XNS" -> R.drawable.xns
        "XOR" -> R.drawable.xor
        "XSN" -> R.drawable.xsn
        "XTZ" -> R.drawable.xtz
        "XVG" -> R.drawable.xvg
        "XYO" -> R.drawable.xyo
        "XZC" -> R.drawable.xzc
        "YFI" -> R.drawable.yfi
        "YOYO" -> R.drawable.yoyo
        "ZAI" -> R.drawable.zai
        "ZEC" -> R.drawable.zec
        "ZRX" -> R.drawable.zrx
        else -> R.drawable.question_sign
    }
}